name: first
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  firebase_messaging_platform_interface: ^4.6.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
#  http: ^0.13.5
#  web_socket_channel: ^3.0.1
#  searchable_paginated_dropdown: ^1.3.0
#  dio: ^5.3.3
#  webview_flutter: ^4.8.0
#  dropdown_search: ^6.0.1
#  geocoding: ^2.1.0
#  google_maps_flutter: ^2.3.0
#  http: ^1.2.2
#  flutter_paypal_payment: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
